<package format="3"><name>sar_mission</name><version>0.1.0</version><description>Mission and registry</description><maintainer email="student@example.com">SAR Team</maintainer><license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend><depend>rclpy</depend><depend>geometry_msgs</depend><depend>sar_interfaces</depend><exec_depend>nav2_simple_commander</exec_depend><exec_depend>nav_msgs</exec_depend><exec_depend>sensor_msgs</exec_depend><exec_depend>visualization_msgs</exec_depend><exec_depend>python3-yaml</exec_depend><export><build_type>ament_python</build_type></export></package>
